// Generated by CoffeeScript 1.6.3
(function() {
  var Customer, Drink, FoodItem, Menu, Order, Plate, Restaurant, avocado, bean, brownRice, burrito, ice, lemon, margarita, me, myOrder, myResturant, restaurantMenu, salt, tequilla, tomato, water;

  FoodItem = function(name, calories, vegan, glutenFree, citrusFree) {
    var toString;
    this.name = name;
    this.calories = calories;
    if (vegan === true) {
      this.vegan = "is vegan";
    } else {
      this.vegan = "is not vegan";
    }
    if (glutenFree === true) {
      this.glutenFree = "is gluten-free";
    } else {
      this.glutenFree = "is not gluten-free";
    }
    if (citrusFree === true) {
      this.citrusFree = "is a citrus";
    } else {
      this.citrusFree = "is not citrus";
    }
    this.toString = toString = function() {
      return this.name.charAt(0).toUpperCase() + this.name.slice(1) + " has " + this.calories + " calories. It is " + this.vegan + ", " + this.citrusFree + " and " + this.glutenFree + ".";
    };
    return this;
  };

  Drink = function(name, description, items) {
    this.name = name;
    this.description = description;
    this.items = items;
    return this;
  };

  Drink.prototype.toString = function() {
    var i, itemsArr, itemsToStringArr;
    itemsArr = [];
    i = 0;
    while (i < this.items.length) {
      itemsArr.push(this.items[i].name);
      i++;
    }
    itemsToStringArr = [];
    i = 0;
    while (i < this.items.length) {
      itemsToStringArr.push(this.items[i].toString());
      i++;
    }
    return this.name.charAt(0).toUpperCase() + this.name.slice(1) + " is " + this.description + ".\nIt is made of " + itemsArr.join(" and ") + ".\n" + itemsToStringArr.join("\n");
  };

  Plate = function(name, description, price, items) {
    this.name = name;
    this.description = description;
    this.price = price;
    return this.items = items;
  };

  Plate.prototype.toString = function() {
    var i, itemsArr, itemsToStringArr;
    itemsArr = [];
    i = 0;
    while (i < this.items.length) {
      itemsArr.push(this.items[i].name);
      i++;
    }
    itemsToStringArr = [];
    i = 0;
    while (i < this.items.length) {
      itemsToStringArr.push(this.items[i].toString());
      i++;
    }
    return this.name.charAt(0).toUpperCase() + this.name.slice(1) + " is a " + this.description + ".\nIt costs $" + this.price + " and is made of " + itemsArr.join(" and ") + ".\n" + itemsToStringArr.join("\n");
  };

  Plate.prototype.isVegan = function() {
    var i;
    i = 0;
    while (i < this.items.length) {
      if (this.items[i].vegan === "non-vegan") {
        return false;
      }
      i++;
    }
    return true;
  };

  Plate.prototype.isGlutenFree = function() {
    var i;
    i = 0;
    while (i < this.items.length) {
      if (this.items[i].glutenFree === "not gluten-free") {
        return false;
      }
      i++;
    }
    return true;
  };

  Plate.prototype.isCitrusFree = function() {
    var i;
    i = 0;
    while (i < this.items.length) {
      if (this.items[i].citrusFree === "a citrus") {
        return false;
      }
      i++;
    }
    return true;
  };

  Order = function(plates) {
    return this.plates = plates;
  };

  Order.prototype.toString = function() {
    var i, platesArr, platesToStringArr;
    platesArr = [];
    i = 0;
    while (i < this.plates.length) {
      platesArr.push(this.plates[i].name);
      i++;
    }
    platesToStringArr = [];
    i = 0;
    while (i < this.plates.length) {
      platesToStringArr.push(this.plates[i].toString());
      i++;
    }
    return "This order contains " + this.plates.length + " plates: " + platesArr.join(", ") + ".\n" + platesToStringArr.join("\n\n");
  };

  Menu = function(plates) {
    return this.plates = plates;
  };

  Menu.prototype.toString = function() {
    var i, platesArr, platesToStringArr;
    platesArr = [];
    i = 0;
    while (i < this.plates.length) {
      platesArr.push(this.plates[i].name);
      i++;
    }
    platesToStringArr = [];
    i = 0;
    while (i < this.plates.length) {
      platesToStringArr.push(this.plates[i].toString());
      i++;
    }
    return "The menu contains " + this.plates.length + " plates: " + platesArr.join(", ") + ".\n" + platesToStringArr.join("\n\n");
  };

  Restaurant = function(name, description, menu) {
    this.name = name;
    this.description = description;
    return this.menu = menu;
  };

  Restaurant.prototype.toString = function() {
    return "This is a " + this.description + " restaurant called " + this.name + ".\n" + this.menu.toString() + ".";
  };

  Customer = function(dietaryPreference) {
    return this.dietaryPreference = dietaryPreference;
  };

  Customer.prototype.toString = function() {
    return "This customer's dietary preference is: " + this.dietaryPreference + ".";
  };

  me = new Customer("low-carb");

  console.log(me.toString());

  bean = new FoodItem("bean", 100, true, true, true);

  brownRice = new FoodItem("brownRice", 60, true, true, true);

  avocado = new FoodItem("avocado", 80, true, true, true);

  tomato = new FoodItem("tomato", 600, true, true, true);

  lemon = new FoodItem("lemon", 20, true, true, false);

  water = new FoodItem("water", 0, true, true, true);

  salt = new FoodItem("salt", 0, true, true, true);

  ice = new FoodItem("ice", 0, true, true, true);

  tequilla = new FoodItem("tequilla", 100, true, true, true);

  margarita = new Drink("margarita", "tequilla fun", [lemon, water, salt, ice, tequilla]);

  console.log(margarita.toString());

  burrito = new Plate("burrito", "goodness wrapped in a tortilla", 8, [bean, brownRice, avocado, tomato]);

  console.log(burito.toString());

  restaurantMenu = new Menu([margarita, burrito]);

  console.log(restaurantMenu.toString());

  myOrder = new Order([margarita, burrito]);

  console.log(myOrder.toString());

  myResturant = new Restaurant("TacoVille", "don't eat here", restaurantMenu);

  console.log(chineseResturant.toString());

}).call(this);
